export const GET_EXERCICES = 'GET_EXERCICES';
export const CREATE_EXERCICE = 'CREATE_EXERCICE';
export const EDIT_EXERCICE = 'EDIT_EXERCICE';
export const DELETE_EXERCICE = 'DELETE_EXERCICE';
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
